app/products/models.py
import re

from django.conf import settings
from django.db import models


class Product(models.Model):
    PATTERN_HASHTAG = re.compile(r'#(\w+)')

    title = models.CharField(max_length=200)
    company = models.CharField(max_length=200)
    type = models.CharField(max_length=200)
    photos = models.ImageField(upload_to='product', blank=True)
    content = models.TextField(blank=True)

    base_shipping_charge = models.PositiveIntegerField(default=0)
    free_shipping_charge_limit = models.PositiveIntegerField(default=0)
    extra_shipping_charge = models.PositiveIntegerField(default=0)

    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)

    created_at = models.DateTimeField(auto_now_add=True)
    tags = models.ManyToManyField('HashTag', blank=True)

    like_users = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        blank=True,
        related_name='like_products',
    )

    class Meta:
        ordering = ['-pk']

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        for tag_name in re.findall(self.PATTERN_HASHTAG, self.content):
            tag, tag_created = HashTag.objects.get_or_create(name=tag_name)
            self.tags.add(tag)

    def __str__(self):
        return f'{self.title}'

    @property
    def content_html(self):
        return re.sub(
            r'#(?P<tag>\w+)',
            '<a href="/products/tags/\g<tag>">#\g<tag></a>',
            self.content,
        )


class HashTag(models.Model):
    name = models.CharField(max_length=20)

    def __str__(self):
        return f'HashTag (self.name)'


class Comment(models.Model):
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    parent_comment = models.ForeignKey(
        'self',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='comments',
    )
    _author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='comments',
    )
    _content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return f'Comment (product: {self.product.pk}, author: {self.author.username})'

    @property
    def author(self):
        if self.is_deleted:
            return None
        return self._author

    @property
    def content(self):
        if self.is_deleted:
            return '삭제된 댓글입니다'
        return self._content

    def delete(self, *args, **kwargs):
        self.is_deleted = True
        self.save()


class Inquiry(models.Model):
    product = models.ForeignKey(
        Product,
        on_delete=models.CASCADE,
        related_name='inquiries',
    )
    parent_inquiry = models.ForeignKey(
        'self',
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='inquiries',
    )
    _author = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_name='inquiries',
    )
    _content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    is_deleted = models.BooleanField(default=False)

    def __str__(self):
        return f'Comment (product: {self.product.pk}, author: {self.author.username})'

    @property
    def author(self):
        if self.is_deleted:
            return None
        return self._author

    @property
    def content(self):
        if self.is_deleted:
            return '삭제된 댓글입니다'
        return self._content

    def delete(self, *args, **kwargs):
        self.is_deleted = True
        self.save()

app/products/forms.py
from django import forms
from .models import Product


class ProductModelForm(forms.ModelForm):
    # field정의를 직접 하지 않음
    #  (어떤 field를 사용할 것인지만 class Meta에 기록)
    class Meta:
        model = Product
        fields = (
            'title',
            'company',
            'type',
            'photos',
            'content',
            'base_shipping_charge',
            'free_shipping_charge_limit',
            'extra_shipping_charge',
        )


class ProductForm(forms.Form):

    title = forms.CharField(
        label='제목',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )

    company = forms.CharField(
        label='브랜드명',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )

    type = forms.CharField(
        label='제품유형',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )

    photos = forms.ImageField(
        label='사진',
        widget=forms.FileInput(
            attrs={
                'class': 'form-control',
                'multiple': True,
            }
        )
    )
    content = forms.CharField(
        label='제품설명',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )

    base_shipping_charge = forms.IntegerField(
        label='기본배송료',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )

    free_shipping_charge_limit = forms.IntegerField(
        label='무료배송료조건',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )

    extra_shipping_charge = forms.IntegerField(
        label='제주/도서산간지역 추가비용',
        widget=forms.TextInput(
            attrs={
                'class': 'form-control',
            }
        )
    )

    def save(self, author):
        return Product.objects.create(
            author=author,
            title=self.cleaned_data['title'],
            company=self.cleaned_data['company'],
            type=self.cleaned_data['type'],
            photos=self.cleaned_data['photos'],
            content=self.cleaned_data['content'],
            base_shipping_charge=self.cleaned_data['base_shipping_charge'],
            free_shipping_charge_limit=self.cleaned_data['base_shipping_charge_limit'],
            extra_shipping_charge=self.cleaned_data['extra_shipping_charge'],
        )

app/products/apis/__init__.py
from rest_framework import generics

from ..models import Product
from ..serializers import ProductSerializer


class ProductList(generics.ListAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer

    # def get_queryset(self):
    #     user = self.request.user
    #
    #     print(user, '실행ㅁㅁㅁㄴㅇㅁㄴㅇㅁㄴㅇㅁㄴㅇ ')
    #
    #     return Product.objects.filter(author=user)


class ProductDetail(generics.RetrieveAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer


class ProductCreate(generics.ListCreateAPIView):
    queryset = Product.objects.all()
    serializer_class = ProductSerializer

app/products/urls/views.py
from django.urls import path

from .. import views

app_name = 'products'
urlpatterns = [
    # config.urls
    #  path('products/', include(이 urlpatterns))
    path('', views.product_list, name='product-list'),
    path('tags/<str:tag>/', views.search_product_list, name='search-product-list'),
    path('<int:pk>/', views.product_detail, name='product-detail'),
    path('<int:pk>/delete/', views.product_delete, name='product-delete'),
    path('<int:pk>/like/', views.product_like, name='product-like'),
    path('<int:pk>/dislike/', views.product_dislike, name='product-dislike'),
    path('create/', views.product_create, name='product-create'),
    path('<int:product_pk>/comment/create/',
         views.comment_create,
         name='comment-create'),
    path('<int:product_pk>/comment/<int:comment_pk>/create/',
         views.comment_create,
         name='child-comment-create'),
]

app/products/views/__init__.py
from .comment_create import *
from .post_create import *
from .post_delete import *
from .post_detail import *
from .post_like import *
from .post_list import *
from .post_search import *

app/products/views/comment_create.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect
from django.views.decorators.http import require_POST

from ..models import Product, Comment

__all__ = (
    'comment_create',
)


@login_required
@require_POST
def comment_create(request, product_pk, comment_pk=None):
    product = get_object_or_404(Product, pk=product_pk)
    parent_comment = get_object_or_404(Comment, pk=comment_pk) if comment_pk else None
    product.comments.create(
        _author=request.user,
        _content=request.POST.get('content'),
        parent_comment=parent_comment,
    )
    return redirect('products:product-detail', pk=product_pk)

app/products/views/post_create.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect

from ..forms import ProductModelForm, ProductForm
from ..models import Product

__all__ = (
    'product_create',
)


def product_create(request):
    # PostModelForm을 사용
    #  form = PostModelForm(request.POST, request.FILES)
    #  post = form.save(commit=False)
    #  post.author = request.user
    #  post.save()
    if request.method == 'POST':
        form = ProductModelForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(commit=False)
            product.author = request.user
            product.save()
            return redirect('products:product-detail', pk=product.pk)
    else:
        form = ProductModelForm()
    context = {
        'form': form,
    }
    return render(request, 'products/product_create.html', context)


@login_required
def product_create_with_form(request):
    if request.method == 'POST':
        form = ProductForm(request.POST, request.FILES)
        if form.is_valid():
            product = form.save(author=request.user)
            return redirect('products:product-detail', pk=product.pk)
    else:
        form = ProductForm()
    context = {
        'form': form,
    }
    return render(request, 'products/product_create.html', context)


def product_create_without_form(request):
    if request.method == 'POST':
        product = Product(
            author=request.user,
            photo=request.FILES['photo'],
            content=request.POST['content'],
        )
        product.save()
        return redirect('products:product-detail', pk=product.pk)
    return render(request, 'products/product_create.html')

app/products/views/post_delete.py
from django.contrib.auth.decorators import login_required
from django.core.exceptions import PermissionDenied
from django.shortcuts import redirect, get_object_or_404
from django.views.decorators.http import require_POST

from ..models import Product

__all__ = (
    'product_delete',
)


@require_POST
@login_required
def product_delete(request, pk):
    # if request.method != 'POST':
    #     return HttpResponseNotAllowed()
    # if not request.user.is_authenticated:
    #     return redirect('members:login')
    product = get_object_or_404(Product, pk=pk)
    if product.author != request.user:
        raise PermissionDenied('지울 권한이 없습니다')
    product.delete()
    return redirect('products:product-list')

app/products/views/post_detail.py
from django.shortcuts import render

from ..models import Product, Comment

__all__ = (
    'product_detail',
)


def product_detail(request, pk):
    product = Product.objects.get(pk=pk)
    comment = Comment.objects.filter(product=product)
    context = {
        'product': product,
        'comments': comment,
    }
    return render(request, 'products/product_detail.html', context)

app/products/views/post_like.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect
from django.views.decorators.http import require_POST

from ..models import Product

__all__ = (
    'product_like',
    'product_dislike',
    'product_like_toggle',
)


@login_required
@require_POST
def product_like(request, pk):
    product = get_object_or_404(Product, pk=pk)
    request.user.like_posts.add(product)
    return redirect('products:product-detail', pk=pk)


@login_required
@require_POST
def product_dislike(request, pk):
    product = get_object_or_404(Product, pk=pk)
    request.user.like_posts.remove(product)
    return redirect('products:product-detail', pk=pk)


@login_required
@require_POST
def product_like_toggle(request, pk):
    product = get_object_or_404(Product, pk=pk)
    if request.user.like_posts.filter(post=product).exists():
        request.user.like_posts.remove(product)
    else:
        request.user.like_posts.add(product)
    return redirect('products:product-detail', pk=pk)

app/products/views/post_list.py
from django.shortcuts import render

from ..models import Product

__all__ = (
    'product_list',
)


def product_list(request):
    products = Product.objects.all()
    context = {
        'products': products,
    }
    return render(request, 'products/product_list.html', context)

app/products/views/post_search.py
from django.shortcuts import render

from ..models import Product

__all__ = (
    'search_product_list',
)


def search_product_list(request, tag):
    products = Product.objects.filter(tags__name=tag).distinct()
    context = {
        'products': products,
    }
    return render(request, 'products/search_product_list.html', context)

app/templates/products/product_create.html
{% extends 'base.html' %}

{% block content %}
<div>

	<form action="" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form.non_field_errors }}
		{% for field in form %}
		<div class="form-group">
			<label for="{{ field.id_for_label }}">{{ field.label }}</label>
			{{ field }}
			{{ field.errors }}
		</div>
		{% endfor %}
		<button type="submit" class="btn btn-primary btn-block">작성</button>
	</form>
</div>
{% endblock %}

app/templates/products/product_create_without_form.html
{% extends 'base.html' %}

{% block content %}
<div>

	<form action="" method="POST" enctype="multipart/form-data">
		{% csrf_token %}
		<div class="form-group">
			<label for="id_photo">사진</label>
			<input id="id_photo" type="file" name="photo" class="form-control">
		</div>

		<div class="form-group">
			<label for="id_content">설명</label>
			<input id="id_content" type="text" name="content" class="form-control">
		</div>

		<button type="submit" class="btn btn-primary btn-block">작성</button>
	</form>
</div>
{% endblock %}

app/templates/products/product_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">

    <div class="row">
        <div class="col-sm-6">
            <img style="width:100%;" class="product-image-size" src="{{product.photos.url}}" alt="{{product.photos}}">
        </div>
        <div class="col-sm-6">

        </div>
    </div>

    <div class="row">
        <div class="mt-2">
            {% if product.author.img_profile %}
            <img class="rounded-circle float-left" style="width:50px; height:50px;"
                 src="{{ product.author.img_profile.url }}" alt="">
            {% else %}
            {% load static %}
            <img class="rounded-circle float-left" style="width:50px; height:50px;"
                 src="{% static 'images/blank_user.jpg' %}" alt="">
            {% endif %}

        </div>
        <p style="line-height: 50px; font-size: 20px; margin-left: 20px; font-weight:bold;">{{product.author}}</p>

    </div>

    <div class="row">

        <p>{{product.content}}</p>
    </div>

    <div class="row">
        <form class="float-left" action="{% url 'products:comment-create' product_pk=product.pk %}" method="POST">
            {% csrf_token %}
            <input type="text" placeholder="댓글 달기" name="content">
            <button type="submit" class="btn btn-success">댓글 등록</button>
        </form>

        <form class="" action="{% url 'products:product-delete' pk=product.pk %}" method="POST">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger">글삭제</button>
        </form>
    </div>


    <!-- comment 가 있으면 유저이미지 가져오기 -->
    {% for user in user.commented_user.all %}
    {% if user.img_profile and product.comments_of_product.all %}
    <div class="row">
        {{ user.commented_user}}
        <div class="col-md-6">
            <img class="rounded-circle float-left" style="width:50px; height:50px;"
                 src="{{ user.img_profile.url }}" alt="">
            <div>
                <p class="layout-user-name">{{ user.username }}</p>
            </div>
            {% elif not user.img_profile and product.comments_of_product.all %}
            {% load static %}
            <img class="rounded-circle float-left" style="width:50px; height:50px;"
                 src="{% static 'images/blank_user.jpg' %}" alt="">
            <div>
                <p class="layout-user-name">{{ user.username }}</p>
            </div>
            {% endif %}
            {% endfor %}
            <ul style="list-style:none; padding:0; margin:0;">
                {% for comment in comments %}
                <li style="text-align: justify;">
                    {% if comment.author.img_profile %}
                    <img class="rounded-circle float-left" style="width:50px; height:50px;"
                         src="{{comment.author.img_profile.url}}" alt="">
                    {% endif %}
                    <span style="line-height: 50px; font-size: 20px; margin-left: 20px; font-weight:bold;">{{comment.author.username}}</span>
                    <p style="margin-top:5px;">
                        {{comment.content}}
                    </p>

                </li>
                {% endfor%}
            </ul>
        </div>
    </div>
</div>

{% endblock %}

app/templates/products/product_list.html
{% extends 'base.html' %}

{% block content %}
	{% for product in products %}
		{% include 'include/products/product.html' %}
	{% endfor %}
{% endblock %}

app/templates/products/product_option_create.html
{% extends 'base.html' %}

{% block content %}
<div>

	<form action="" method="POST" enctype="multipart/form-data">
		{% csrf_token %}


		<button type="submit" class="btn btn-primary btn-block">작성</button>
	</form>
</div>
{% endblock %}

app/templates/products/search_product_list.html
{% extends 'base.html' %}

{% block content %}
	<div class="row">
	{% for product in products %}
		<div class="card mb-3 col-4">
			<div class="card-header">
				<div>
					<!--
						1. app/static폴더 만들기
						2. settings.py에 STATIC_DIR변수에 해당 경로 추가
						3. STATICFILES_DIRS에 위 변수 추가
						4. 아래에서 product.author.img_profile이 존재하지 않으면
								/static/images/blank_user.png <- 이 경로를 src로 사용한다
								이 때, 'static'태그를 사용

						숙제1. 댓글달기 구현
						숙제2. Post좋아요 구현 (현재 좋아요 상태인지 표시, 좋아요 상태면 해제하도록 함)
					-->
					<div class="float-left">
						{% if product.author.img_profile %}
						<img src="{{ product.author.img_profile.url }}"
						     style="width: 30px;"
						     class="rounded-circle float-left mr-1"
						     alt="">
						{% endif %}
						<span>{{ product.author.username }}</span>
						<form action="" method="POST" style="display: inline-block;">
							{% csrf_token %}
							<button type="submit" class="btn btn-outline-primary btn-sm">+ Follow</button>
						</form>
					</div>
					<form action="{% url 'products:product-delete' pk=product.pk %}" method="POST" class="float-right">
						{% csrf_token %}
						<button class="btn btn-danger btn-sm">지우기</button>
					</form>
				</div>
			</div>

			<div class="card-body p-0">
				{% if product.photo %}
				<img width="100%" src="{{ product.photo.url }}" alt="">
				{% endif %}

				{% if product.tags.exists %}
					<div class="container p-2">
						<p>{{ product.content_html|safe|linebreaksbr }}</p>
					</div>
				{% endif %}
			</div>
		</div>
	{% endfor %}
	</div>
{% endblock %}